---
- name: create storage file
  shell: dd if=/dev/zero of=/var/storage.img bs=1M count=2048
  tags:
    - storage-setup

- name: losetup device
  shell: |
    loop_dev=`losetup -a |grep "/var/storage.img"|awk -F':' '{print $1}'`
    if [ -z $loop_dev ]; then
      losetup -f --show /var/storage.img
    else
      echo $loop_dev
    fi
  tags:
    - storage-setup

- name: create physical volume (TODO update hardcoded loop0)
  shell: pvcreate --metadatasize 2048 /dev/loop0
  tags:
    - storage-setup

- name: create virtual volume
  shell: vgcreate cinder-volumes /dev/loop0
  tags:
    - storage-setup

- name: install nfs packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - nfs-kernel-server
    - portmap
    - nfs-common
  tags:
    - storage-setup
    - storage-nfs

- name: Create nfs data directory
  file: path="{{ item }}" state="directory"
  with_items:
    - "/vol/cinder"
    - "/images"
  tags:
    - storage-setup
    - storage-nfs

# TODO use template to render dir
- name: configure nfs exports
  template:
    src: "exports.j2"
    dest: "/etc/exports"
  tags:
    - storage-setup
    - storage-nfs

# TODO use notify
- name: restart nfs server
  service: name={{ item }}  state=restarted enabled=yes
  with_items:
    - nfs-kernel-server
  tags:
    - storage-setup
    - storage-nfs
